usb: Stitching adbckeck and usb-normalboot together
This commit runs the newly introduced adbcheck application.
Immediately after running, it obtains it's return value and stores it in adb_setting.

diff --git a/recipes-proprietary/usb-normalboot/files/init.d/usb b/recipes-proprietary/usb-normalboot/files/init.d/usb
--- a/recipes-proprietary/usb-normalboot/files/init.d/usb
+++ b/recipes-proprietary/usb-normalboot/files/init.d/usb
@@ -53,8 +53,9 @@
 
 # Starts the USB Android Gadget.
 
-# Set variable adb_setting to one, to test this script for now
-adb_setting=1
+# Run adbcheck and store return value in adb_setting for use in shell script
+/usr/bin/adbcheck
+adb_setting=$(echo $?)
 
 if [ ! "$adb_setting" = "1" ];
 then
