Replace recover boot usb init script

diff --git a/recipes-proprietary/usb-recoveryboot/files/usb b/recipes-proprietary/usb-recoveryboot/files/usb
--- a/recipes-proprietary/usb-recoveryboot/files/usb
+++ b/recipes-proprietary/usb-recoveryboot/files/usb
@@ -24,40 +24,104 @@
 # (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 # SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 
-# Start Modem's USB Gadget
-# get soc platform to update product related information
-num="0"
-mode="hsusb"
+# Starts the USB Android Gadget.
 
-pkill adbd
-
-mkdir -p /dev/usb-ffs/adb
-mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
-mount -o remount,gid=5,mode=620 /dev/pts
-echo hsusb > /sys/bus/platform/devices/usb_bam/enable
-echo 0 > /sys/class/android_usb/android0/enable
-echo 0125 > /sys/class/android_usb/android0/idProduct
-echo 27C7 > /sys/class/android_usb/android0/idVendor
-echo diag > /sys/class/android_usb/android0/f_diag/clients
-echo 239 > /sys/class/android_usb/android0/bDeviceClass
-echo 2 > /sys/class/android_usb/android0/bDeviceSubClass
-echo 1 > /sys/class/android_usb/android0/bDeviceProtocol
-# echo tty,smd,smd> /sys/class/android_usb/android0/f_serial/transports
-
-echo smd,smd,smd,tty > /sys/class/android_usb/android0/f_serial/transports
-
-echo QTI,BAM_DMUX > /sys/class/android_usb/android0/f_rmnet/transports
-echo BAM_DMUX > /sys/class/android_usb/android0/f_usb_mbim/mbim_transports
-# echo diag,serial,rmnet,ffs,audio > /sys/class/android_usb/android0/functions
-echo diag,serial,rmnet,adb > /sys/class/android_usb/android0/functions
-echo adb > /sys/class/android_usb/android0/f_ffs/aliases
-echo 1 > /sys/class/android_usb/android0/remote_wakeup
-echo 1 > /sys/class/android_usb/android0/f_rndis/wceis
-
-echo diag,serial,rmnet,ffs > /sys/class/android_usb/android0/functions
-# Quectel Wireless Solutions Co., Ltd. EC25 LTE modem
-echo "Quectel Wireless Solutions Co., Ltd." > /sys/class/android_usb/android0/iManufacturer
-echo "EC25 LTE modem" > /sys/class/android_usb/android0/iProduct
-sleep 2
-echo 1 > /sys/class/android_usb/android0/enable
-/etc/init.d/adbd start
+case "$1" in
+    start)
+        if [ -d /sys/class/android_usb/android0/f_ffs ]
+        then
+            echo adb > /sys/class/android_usb/android0/f_ffs/aliases
+        fi
+        
+        # get soc platform to update product related information
+        if [ -f /sys/devices/soc0/hw_platform ]; then
+            socplatform=$(cat /sys/devices/soc0/machine) 2> /dev/null
+            soc_hwplatform=$(cat /sys/devices/soc0/hw_platform)
+        else
+            socplatform=$(cat /sys/devices/system/soc/soc0/machine) 2> /dev/null
+        fi
+        
+        # find serialno from cmdline
+        cmdline=$(cat /proc/cmdline) 2> /dev/null
+        strsearch="androidboot.serialno="
+        if echo "$cmdline" | grep -q "$strsearch"; then
+            startsearch=${cmdline#*$strsearch}
+            pos=$(( ${#cmdline} - ${#startsearch}))
+            serialno=${cmdline:$pos:8}
+        else
+            echo "serialno not found with cmdline, use default"
+            serialno="12345678"
+        fi
+        
+        msm_serial=$(cat /sys/devices/soc0/serial_number)
+        msm_serial_hex=$(printf %08X "$msm_serial")
+        product_string="$socplatform-$soc_hwplatform _SN:$msm_serial_hex"
+        
+        # try to mount configfs, and create instance of USB functions if it goes through
+        mount -t configfs none /sys/kernel/config
+        if [ -d /sys/kernel/config/usb_gadget ]; then
+            echo "Configuring the USB gadget using ConfigFS..."
+            cd /sys/kernel/config/usb_gadget || ! echo "Path '/sys/kernel/config/usb_gadget' not found"
+            mkdir g1
+            cd g1 || ! echo "Failed to create 'g1' in previous step"
+            mkdir strings/0x409
+            mkdir configs/b.1
+            mkdir configs/b.1/strings/0x409
+            mkdir functions/mass_storage.0
+            mkdir functions/ffs.adb
+            mkdir functions/diag.diag
+            mkdir functions/cser.dun.0
+            mkdir functions/cser.nmea.1
+            mkdir functions/rmnet_bam.rmnet
+            mkdir functions/ncm.0
+            echo "$serialno" > strings/0x409/serialnumber
+            echo "QCOM" > strings/0x409/manufacturer
+            echo "$socplatform" > strings/0x409/product
+            echo "$product_string" > /config/usb_gadget/g1/strings/0x409/product
+            setprop sys.usb.configfs 1
+        fi
+        
+        if [ -d /sys/class/android_usb/android0 ]
+        then
+            echo "$product_string" > /sys/class/android_usb/android0/iProduct
+        fi
+        
+        # mount functionfs
+        mkdir -p /dev/usb-ffs/adb
+        mount -o uid=2000,gid=2000 -t functionfs adb /dev/usb-ffs/adb
+        mount -o remount,gid=5,mode=620 /dev/pts
+        echo adb > /sys/class/android_usb/android0/f_ffs/aliases
+        echo ffs > /sys/class/android_usb/android0/functions
+        
+        echo 0 > /sys/class/android_usb/android0/enable
+        echo 0125 > /sys/class/android_usb/android0/idProduct
+        echo 2C7C > /sys/class/android_usb/android0/idVendor
+        echo diag > /sys/class/android_usb/android0/f_diag/clients
+        echo 239 > /sys/class/android_usb/android0/bDeviceClass
+        echo 2 > /sys/class/android_usb/android0/bDeviceSubClass
+        echo 1 > /sys/class/android_usb/android0/bDeviceProtocol
+        echo tty,smd,smd > /sys/class/android_usb/android0/f_serial/transports
+        echo QTI,BAM_DMUX > /sys/class/android_usb/android0/f_rmnet/transports
+        echo BAM_DMUX > /sys/class/android_usb/android0/f_usb_mbim/mbim_transports
+        echo diag,serial,rmnet,ffs > /sys/class/android_usb/android0/functions        
+        echo 1 > /sys/class/android_usb/android0/remote_wakeup
+        echo 1 > /sys/class/android_usb/android0/f_rndis/wceis
+        #sleep 10 # Wait 10 seconds here to give time to openqti to settle
+        echo "Quectel, Incorporated" > /sys/class/android_usb/android0/iManufacturer
+        echo "LTE Module" > /sys/class/android_usb/android0/iProduct
+        echo 1 > /sys/class/android_usb/android0/enable
+    ;;
+    
+    stop)
+        echo "Stopping USB Android Gadget"
+    ;;
+    
+    restart)
+        $0 stop
+        $0 start
+    ;;
+    *)
+        echo "Usage usb { start | stop | restart}" >&2
+        exit 1
+    ;;
+esac
